/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetApplicationRouteImport } from './routes/vet-application'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TelemedicineRouteImport } from './routes/telemedicine'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SpecializationsRouteImport } from './routes/specializations'
import { Route as SecondOpinionRouteImport } from './routes/second-opinion'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdoptionRouteImport } from './routes/adoption'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as RegistrationPoultryRouteImport } from './routes/registration.poultry'
import { Route as RegistrationPetRouteImport } from './routes/registration.pet'
import { Route as RegistrationDairyRouteImport } from './routes/registration.dairy'
import { Route as MlRecommendationsRouteImport } from './routes/ml.recommendations'
import { Route as MlMatchmakingRouteImport } from './routes/ml.matchmaking'
import { Route as MlChatbotRouteImport } from './routes/ml.chatbot'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ClubsPoultryRouteImport } from './routes/clubs.poultry'
import { Route as ClubsFarmRouteImport } from './routes/clubs.farm'
import { Route as ClubsDogsRouteImport } from './routes/clubs.dogs'
import { Route as ClubsCatsRouteImport } from './routes/clubs.cats'
import { Route as ClubsBirdsHorseRouteImport } from './routes/clubs.birds-horse'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdoptionSlugRouteImport } from './routes/adoption.$slug'

const VetApplicationRoute = VetApplicationRouteImport.update({
  id: '/vet-application',
  path: '/vet-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineRoute = TelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsRoute = SpecializationsRouteImport.update({
  id: '/specializations',
  path: '/specializations',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionRoute = SecondOpinionRouteImport.update({
  id: '/second-opinion',
  path: '/second-opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionRoute = AdoptionRouteImport.update({
  id: '/adoption',
  path: '/adoption',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationPoultryRoute = RegistrationPoultryRouteImport.update({
  id: '/poultry',
  path: '/poultry',
  getParentRoute: () => RegistrationRoute,
} as any)
const RegistrationPetRoute = RegistrationPetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => RegistrationRoute,
} as any)
const RegistrationDairyRoute = RegistrationDairyRouteImport.update({
  id: '/dairy',
  path: '/dairy',
  getParentRoute: () => RegistrationRoute,
} as any)
const MlRecommendationsRoute = MlRecommendationsRouteImport.update({
  id: '/ml/recommendations',
  path: '/ml/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const MlMatchmakingRoute = MlMatchmakingRouteImport.update({
  id: '/ml/matchmaking',
  path: '/ml/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const MlChatbotRoute = MlChatbotRouteImport.update({
  id: '/ml/chatbot',
  path: '/ml/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const ClubsPoultryRoute = ClubsPoultryRouteImport.update({
  id: '/poultry',
  path: '/poultry',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsFarmRoute = ClubsFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsDogsRoute = ClubsDogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsCatsRoute = ClubsCatsRouteImport.update({
  id: '/cats',
  path: '/cats',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsBirdsHorseRoute = ClubsBirdsHorseRouteImport.update({
  id: '/birds-horse',
  path: '/birds-horse',
  getParentRoute: () => ClubsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdoptionSlugRoute = AdoptionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdoptionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRouteWithChildren
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/partners': typeof PartnersRoute
  '/prescription': typeof PrescriptionRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registration': typeof RegistrationRouteWithChildren
  '/second-opinion': typeof SecondOpinionRoute
  '/specializations': typeof SpecializationsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/vet-application': typeof VetApplicationRoute
  '/adoption/$slug': typeof AdoptionSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/clubs/birds-horse': typeof ClubsBirdsHorseRoute
  '/clubs/cats': typeof ClubsCatsRoute
  '/clubs/dogs': typeof ClubsDogsRoute
  '/clubs/farm': typeof ClubsFarmRoute
  '/clubs/poultry': typeof ClubsPoultryRoute
  '/events/$slug': typeof EventsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/ml/chatbot': typeof MlChatbotRoute
  '/ml/matchmaking': typeof MlMatchmakingRoute
  '/ml/recommendations': typeof MlRecommendationsRoute
  '/registration/dairy': typeof RegistrationDairyRoute
  '/registration/pet': typeof RegistrationPetRoute
  '/registration/poultry': typeof RegistrationPoultryRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRouteWithChildren
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/partners': typeof PartnersRoute
  '/prescription': typeof PrescriptionRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registration': typeof RegistrationRouteWithChildren
  '/second-opinion': typeof SecondOpinionRoute
  '/specializations': typeof SpecializationsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/vet-application': typeof VetApplicationRoute
  '/adoption/$slug': typeof AdoptionSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/clubs/birds-horse': typeof ClubsBirdsHorseRoute
  '/clubs/cats': typeof ClubsCatsRoute
  '/clubs/dogs': typeof ClubsDogsRoute
  '/clubs/farm': typeof ClubsFarmRoute
  '/clubs/poultry': typeof ClubsPoultryRoute
  '/events/$slug': typeof EventsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/ml/chatbot': typeof MlChatbotRoute
  '/ml/matchmaking': typeof MlMatchmakingRoute
  '/ml/recommendations': typeof MlRecommendationsRoute
  '/registration/dairy': typeof RegistrationDairyRoute
  '/registration/pet': typeof RegistrationPetRoute
  '/registration/poultry': typeof RegistrationPoultryRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adoption': typeof AdoptionRouteWithChildren
  '/booking': typeof BookingRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRoute
  '/events': typeof EventsRouteWithChildren
  '/faq': typeof FaqRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/membership': typeof MembershipRoute
  '/offers': typeof OffersRoute
  '/partners': typeof PartnersRoute
  '/prescription': typeof PrescriptionRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/registration': typeof RegistrationRouteWithChildren
  '/second-opinion': typeof SecondOpinionRoute
  '/specializations': typeof SpecializationsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/telemedicine': typeof TelemedicineRoute
  '/terms': typeof TermsRoute
  '/vet-application': typeof VetApplicationRoute
  '/adoption/$slug': typeof AdoptionSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/clubs/birds-horse': typeof ClubsBirdsHorseRoute
  '/clubs/cats': typeof ClubsCatsRoute
  '/clubs/dogs': typeof ClubsDogsRoute
  '/clubs/farm': typeof ClubsFarmRoute
  '/clubs/poultry': typeof ClubsPoultryRoute
  '/events/$slug': typeof EventsSlugRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/ml/chatbot': typeof MlChatbotRoute
  '/ml/matchmaking': typeof MlMatchmakingRoute
  '/ml/recommendations': typeof MlRecommendationsRoute
  '/registration/dairy': typeof RegistrationDairyRoute
  '/registration/pet': typeof RegistrationPetRoute
  '/registration/poultry': typeof RegistrationPoultryRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adoption'
    | '/booking'
    | '/careers'
    | '/cart'
    | '/clubs'
    | '/contact'
    | '/doctors'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/membership'
    | '/offers'
    | '/partners'
    | '/prescription'
    | '/pricing'
    | '/privacy'
    | '/registration'
    | '/second-opinion'
    | '/specializations'
    | '/success-stories'
    | '/telemedicine'
    | '/terms'
    | '/vet-application'
    | '/adoption/$slug'
    | '/blogs/$slug'
    | '/clubs/birds-horse'
    | '/clubs/cats'
    | '/clubs/dogs'
    | '/clubs/farm'
    | '/clubs/poultry'
    | '/events/$slug'
    | '/marketplace/$slug'
    | '/ml/chatbot'
    | '/ml/matchmaking'
    | '/ml/recommendations'
    | '/registration/dairy'
    | '/registration/pet'
    | '/registration/poultry'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adoption'
    | '/booking'
    | '/careers'
    | '/cart'
    | '/clubs'
    | '/contact'
    | '/doctors'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/membership'
    | '/offers'
    | '/partners'
    | '/prescription'
    | '/pricing'
    | '/privacy'
    | '/registration'
    | '/second-opinion'
    | '/specializations'
    | '/success-stories'
    | '/telemedicine'
    | '/terms'
    | '/vet-application'
    | '/adoption/$slug'
    | '/blogs/$slug'
    | '/clubs/birds-horse'
    | '/clubs/cats'
    | '/clubs/dogs'
    | '/clubs/farm'
    | '/clubs/poultry'
    | '/events/$slug'
    | '/marketplace/$slug'
    | '/ml/chatbot'
    | '/ml/matchmaking'
    | '/ml/recommendations'
    | '/registration/dairy'
    | '/registration/pet'
    | '/registration/poultry'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adoption'
    | '/booking'
    | '/careers'
    | '/cart'
    | '/clubs'
    | '/contact'
    | '/doctors'
    | '/events'
    | '/faq'
    | '/marketplace'
    | '/membership'
    | '/offers'
    | '/partners'
    | '/prescription'
    | '/pricing'
    | '/privacy'
    | '/registration'
    | '/second-opinion'
    | '/specializations'
    | '/success-stories'
    | '/telemedicine'
    | '/terms'
    | '/vet-application'
    | '/adoption/$slug'
    | '/blogs/$slug'
    | '/clubs/birds-horse'
    | '/clubs/cats'
    | '/clubs/dogs'
    | '/clubs/farm'
    | '/clubs/poultry'
    | '/events/$slug'
    | '/marketplace/$slug'
    | '/ml/chatbot'
    | '/ml/matchmaking'
    | '/ml/recommendations'
    | '/registration/dairy'
    | '/registration/pet'
    | '/registration/poultry'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdoptionRoute: typeof AdoptionRouteWithChildren
  BookingRoute: typeof BookingRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRoute
  EventsRoute: typeof EventsRouteWithChildren
  FaqRoute: typeof FaqRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  MembershipRoute: typeof MembershipRoute
  OffersRoute: typeof OffersRoute
  PartnersRoute: typeof PartnersRoute
  PrescriptionRoute: typeof PrescriptionRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegistrationRoute: typeof RegistrationRouteWithChildren
  SecondOpinionRoute: typeof SecondOpinionRoute
  SpecializationsRoute: typeof SpecializationsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TelemedicineRoute: typeof TelemedicineRoute
  TermsRoute: typeof TermsRoute
  VetApplicationRoute: typeof VetApplicationRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  MlChatbotRoute: typeof MlChatbotRoute
  MlMatchmakingRoute: typeof MlMatchmakingRoute
  MlRecommendationsRoute: typeof MlRecommendationsRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vet-application': {
      id: '/vet-application'
      path: '/vet-application'
      fullPath: '/vet-application'
      preLoaderRoute: typeof VetApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine': {
      id: '/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof TelemedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations': {
      id: '/specializations'
      path: '/specializations'
      fullPath: '/specializations'
      preLoaderRoute: typeof SpecializationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinion': {
      id: '/second-opinion'
      path: '/second-opinion'
      fullPath: '/second-opinion'
      preLoaderRoute: typeof SecondOpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption': {
      id: '/adoption'
      path: '/adoption'
      fullPath: '/adoption'
      preLoaderRoute: typeof AdoptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/poultry': {
      id: '/registration/poultry'
      path: '/poultry'
      fullPath: '/registration/poultry'
      preLoaderRoute: typeof RegistrationPoultryRouteImport
      parentRoute: typeof RegistrationRoute
    }
    '/registration/pet': {
      id: '/registration/pet'
      path: '/pet'
      fullPath: '/registration/pet'
      preLoaderRoute: typeof RegistrationPetRouteImport
      parentRoute: typeof RegistrationRoute
    }
    '/registration/dairy': {
      id: '/registration/dairy'
      path: '/dairy'
      fullPath: '/registration/dairy'
      preLoaderRoute: typeof RegistrationDairyRouteImport
      parentRoute: typeof RegistrationRoute
    }
    '/ml/recommendations': {
      id: '/ml/recommendations'
      path: '/ml/recommendations'
      fullPath: '/ml/recommendations'
      preLoaderRoute: typeof MlRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml/matchmaking': {
      id: '/ml/matchmaking'
      path: '/ml/matchmaking'
      fullPath: '/ml/matchmaking'
      preLoaderRoute: typeof MlMatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml/chatbot': {
      id: '/ml/chatbot'
      path: '/ml/chatbot'
      fullPath: '/ml/chatbot'
      preLoaderRoute: typeof MlChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/clubs/poultry': {
      id: '/clubs/poultry'
      path: '/poultry'
      fullPath: '/clubs/poultry'
      preLoaderRoute: typeof ClubsPoultryRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/farm': {
      id: '/clubs/farm'
      path: '/farm'
      fullPath: '/clubs/farm'
      preLoaderRoute: typeof ClubsFarmRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/dogs': {
      id: '/clubs/dogs'
      path: '/dogs'
      fullPath: '/clubs/dogs'
      preLoaderRoute: typeof ClubsDogsRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/cats': {
      id: '/clubs/cats'
      path: '/cats'
      fullPath: '/clubs/cats'
      preLoaderRoute: typeof ClubsCatsRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/birds-horse': {
      id: '/clubs/birds-horse'
      path: '/birds-horse'
      fullPath: '/clubs/birds-horse'
      preLoaderRoute: typeof ClubsBirdsHorseRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adoption/$slug': {
      id: '/adoption/$slug'
      path: '/$slug'
      fullPath: '/adoption/$slug'
      preLoaderRoute: typeof AdoptionSlugRouteImport
      parentRoute: typeof AdoptionRoute
    }
  }
}

interface AdoptionRouteChildren {
  AdoptionSlugRoute: typeof AdoptionSlugRoute
}

const AdoptionRouteChildren: AdoptionRouteChildren = {
  AdoptionSlugRoute: AdoptionSlugRoute,
}

const AdoptionRouteWithChildren = AdoptionRoute._addFileChildren(
  AdoptionRouteChildren,
)

interface ClubsRouteChildren {
  ClubsBirdsHorseRoute: typeof ClubsBirdsHorseRoute
  ClubsCatsRoute: typeof ClubsCatsRoute
  ClubsDogsRoute: typeof ClubsDogsRoute
  ClubsFarmRoute: typeof ClubsFarmRoute
  ClubsPoultryRoute: typeof ClubsPoultryRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsBirdsHorseRoute: ClubsBirdsHorseRoute,
  ClubsCatsRoute: ClubsCatsRoute,
  ClubsDogsRoute: ClubsDogsRoute,
  ClubsFarmRoute: ClubsFarmRoute,
  ClubsPoultryRoute: ClubsPoultryRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface RegistrationRouteChildren {
  RegistrationDairyRoute: typeof RegistrationDairyRoute
  RegistrationPetRoute: typeof RegistrationPetRoute
  RegistrationPoultryRoute: typeof RegistrationPoultryRoute
}

const RegistrationRouteChildren: RegistrationRouteChildren = {
  RegistrationDairyRoute: RegistrationDairyRoute,
  RegistrationPetRoute: RegistrationPetRoute,
  RegistrationPoultryRoute: RegistrationPoultryRoute,
}

const RegistrationRouteWithChildren = RegistrationRoute._addFileChildren(
  RegistrationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdoptionRoute: AdoptionRouteWithChildren,
  BookingRoute: BookingRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  ClubsRoute: ClubsRouteWithChildren,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRoute,
  EventsRoute: EventsRouteWithChildren,
  FaqRoute: FaqRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  MembershipRoute: MembershipRoute,
  OffersRoute: OffersRoute,
  PartnersRoute: PartnersRoute,
  PrescriptionRoute: PrescriptionRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RegistrationRoute: RegistrationRouteWithChildren,
  SecondOpinionRoute: SecondOpinionRoute,
  SpecializationsRoute: SpecializationsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TelemedicineRoute: TelemedicineRoute,
  TermsRoute: TermsRoute,
  VetApplicationRoute: VetApplicationRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  MlChatbotRoute: MlChatbotRoute,
  MlMatchmakingRoute: MlMatchmakingRoute,
  MlRecommendationsRoute: MlRecommendationsRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
